spring:
  elasticsearch:
    bboss:
      default:
        name: default
        elasticPassword: changeme
        elasticUser: elastic
        elasticsearch:
          dateFormat: yyyy.MM.dd
          discoverHost: false
          rest:
            hostNames: 192.168.137.1:9200
          scrollBlockedWaitTimeout: 0
          scrollThreadCount: 200
          scrollThreadQueue: 200
          showTemplate: true
          sliceScrollBlockedWaitTimeout: 0
          sliceScrollThreadCount: 100
          sliceScrollThreadQueue: 100
          timeZone: Asia/Shanghai
        http:
          connectionRequestTimeout: 50000
          customHttpRequestRetryHandler: org.frameworkset.spi.remote.http.ConnectionResetHttpRequestRetryHandler
          defaultMaxPerRoute: 200
          hostnameVerifier: ''
          keyPassword: ''
          keystore: ''
          maxHeaderCount: 200
          maxLineLength: -1
          maxTotal: 400
          retryTime: 1
          retryInterval: 10000
          staleConnectionCheckEnabled: false
          timeoutConnection: 50000
          timeoutSocket: 50000
          validateAfterInactivity: 200000
      dslfile:
        refreshInterval: -1
      logs:
        name: logs
        elasticPassword: changeme
        elasticUser: elastic
        elasticsearch:
          dateFormat: yyyy.MM.dd
          discoverHost: false
          rest:
            hostNames: localhost:9200
          scrollBlockedWaitTimeout: 0
          scrollThreadCount: 200
          scrollThreadQueue: 200
          showTemplate: true
          sliceScrollBlockedWaitTimeout: 0
          sliceScrollThreadCount: 100
          sliceScrollThreadQueue: 100
          timeZone: Asia/Shanghai
        http:
          connectionRequestTimeout: 50000
          customHttpRequestRetryHandler: org.frameworkset.spi.remote.http.ConnectionResetHttpRequestRetryHandler
          defaultMaxPerRoute: 200
          hostnameVerifier: ''
          keyPassword: ''
          keystore: ''
          maxHeaderCount: 200
          maxLineLength: -1
          maxTotal: 400
          retryTime: 1
          staleConnectionCheckEnabled: false
          timeoutConnection: 50000
          timeoutSocket: 50000
          validateAfterInactivity: 200000

